name: 🐞 Баг-репорт
description: Сообщите о баге, с которым вы столкнулись на сервере
title: "[BUG] Краткое описание проблемы"
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Спасибо, что помогаете нам сделать сервер лучше! Пожалуйста, заполните эту форму как можно подробнее.

  - type: input
    id: username
    attributes:
      label: Ник в игре
      description: Укажите ваш никнейм на сервере
      placeholder: MikhailFurryTest123
    validations:
      required: true

  - type: input
    id: log_link
    attributes:
      label: Ссылка на логи Minecraft (mclo.gs)
      description: Загрузите свои клиентские или серверные логи на [https://mclo.gs](https://mclo.gs) и вставьте ссылку
      placeholder: https://mclo.gs/abc123
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: Описание бага
      description: Опишите, что именно произошло. Что должно было произойти и что случилось на самом деле?
      placeholder: "Например: При попытке открыть сундук — вылетает из игры."
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Как воспроизвести баг?
      description: Опишите пошагово, как можно воспроизвести этот баг.
      placeholder: |
        1. Зашёл на сервер
        2. Написал команду /example
        3. Произошёл сбой
    validations:
      required: true

  - type: input
    id: mc_version
    attributes:
      label: Версия клиента Minecraft
      description: "Укажите версию, на которой вы играли (например: 1.20.1 Fabric, 1.19.4 Vanilla)"
      placeholder: 1.21.1 Fabric
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: Дополнительная информация
      description: Всё, что может помочь в диагностике бага (время, место, локация, окружение и т.п.)
      placeholder: Баг случился около 18:30 МСК на территории города...
    validations:
      required: false
