name: 💡 Предложение / Новая функция
description: Предложите улучшение или новую функцию для сервера
title: "[FEATURE] Введите название предложения"
labels: [Предложение]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Спасибо за ваше предложение! Пожалуйста, постарайтесь описать идею подробно и понятно.

  - type: input
    id: username
    attributes:
      label: Ваш ник в игре
      description: Укажите ваш ник на сервере
      placeholder: MikhailFurryTest123
    validations:
      required: true

  - type: textarea
    id: idea_description
    attributes:
      label: В чём суть предложения?
      description: Опишите идею — что вы хотите добавить или изменить?
      placeholder: "Например: Добавить новую механику торговли между городами..."
    validations:
      required: true

  - type: textarea
    id: why_needed
    attributes:
      label: Почему это стоит добавить?
      description: Объясните, какую проблему решает это предложение, или как оно улучшит игровой опыт.
      placeholder: Это разнообразит RP и даст больше взаимодействия между фракциями.
    validations:
      required: true

  - type: textarea
    id: how_implemented
    attributes:
      label: Как это можно реализовать?
      description: Если у вас есть идеи по реализации — опишите. Это может помочь ускорить внедрение.
      placeholder: "Например: можно использовать плагин TradeManager, или написать кастомный функционал..."
    validations:
      required: false

  - type: textarea
    id: additional_info
    attributes:
      label: Дополнительно
      description: Всё, что вы хотите добавить (примеры, ссылки, схемы и т.п.)
      placeholder: Вдохновлялся сервером XYZ, где была похожая система.
    validations:
      required: false
